dist:     xenial
sudo:     required

language: c

os: linux

compiler: gcc

env:
  global:
    - CODECOV_TOKEN="a659bbeb-783e-4906-8ca9-a66b83df66af"

install:
    - sudo apt-get update
    - sudo apt-get install valgrind
    - sudo apt-get install lcov
    - sudo apt-get install libstdc++6
    - sudo apt-get install cmake
    # Google tests
    - sudo apt-get install libgtest-dev
    - cd /usr/src/gtest
    - sudo cmake .
    - sudo make
    - sudo cp *.a /usr/lib
    - cd -
    
before_script:
    - ./linters/run.sh

script:
    - cmake .
    - make
    - valgrind --tool=memcheck --leak-check=full --leak-resolution=med  --track-origins=yes ./tests.out

after_script:
    - lcov —capture —directory ./CMakeFiles/task_library.dir/project/src —output-file coverage.info
    - bash <(curl -s https://codecov.io/bash)
    - make clean
