dist:     xenial
sudo:     required

language: c

os: linux

compiler: gcc

install:
    - sudo apt-get update
    - sudo apt-get install valgrind
    - sudo apt-get install libstdc++6
    - sudo apt-get install cmake
    # Google tests
    - sudo apt-get install libgtest-dev
    - cd /usr/src/gtest
    - sudo cmake .
    - sudo make
    - sudo cp *.a /usr/lib
    - cd -

jobs:
    include:
        - stage: Linters
          script: ./linters/run.sh
        - stage: Build
          script: cmake .
          script: make
        - stage: Tests
          script: ./tests.out
        - stage: MemCheck
          script: valgrind --tool=memcheck --leak-check=full --show-leak-types = all --leak-resolution=med  --track-origins=yes ./tests.out
after_script:
    - make clean
