# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/timofey/TechnoPark/Tekhnopark-C

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/timofey/TechnoPark/Tekhnopark-C

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/timofey/TechnoPark/Tekhnopark-C/CMakeFiles /home/timofey/TechnoPark/Tekhnopark-C/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/timofey/TechnoPark/Tekhnopark-C/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named url_parse_std_lib

# Build rule for target.
url_parse_std_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 url_parse_std_lib
.PHONY : url_parse_std_lib

# fast build rule for target.
url_parse_std_lib/fast:
	$(MAKE) -f CMakeFiles/url_parse_std_lib.dir/build.make CMakeFiles/url_parse_std_lib.dir/build
.PHONY : url_parse_std_lib/fast

#=============================================================================
# Target rules for targets named tests

# Build rule for target.
tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tests
.PHONY : tests

# fast build rule for target.
tests/fast:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/build
.PHONY : tests/fast

#=============================================================================
# Target rules for targets named prog

# Build rule for target.
prog: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 prog
.PHONY : prog

# fast build rule for target.
prog/fast:
	$(MAKE) -f CMakeFiles/prog.dir/build.make CMakeFiles/prog.dir/build
.PHONY : prog/fast

project/src/main.o: project/src/main.c.o

.PHONY : project/src/main.o

# target to build an object file
project/src/main.c.o:
	$(MAKE) -f CMakeFiles/url_parse_std_lib.dir/build.make CMakeFiles/url_parse_std_lib.dir/project/src/main.c.o
	$(MAKE) -f CMakeFiles/prog.dir/build.make CMakeFiles/prog.dir/project/src/main.c.o
.PHONY : project/src/main.c.o

project/src/main.i: project/src/main.c.i

.PHONY : project/src/main.i

# target to preprocess a source file
project/src/main.c.i:
	$(MAKE) -f CMakeFiles/url_parse_std_lib.dir/build.make CMakeFiles/url_parse_std_lib.dir/project/src/main.c.i
	$(MAKE) -f CMakeFiles/prog.dir/build.make CMakeFiles/prog.dir/project/src/main.c.i
.PHONY : project/src/main.c.i

project/src/main.s: project/src/main.c.s

.PHONY : project/src/main.s

# target to generate assembly for a file
project/src/main.c.s:
	$(MAKE) -f CMakeFiles/url_parse_std_lib.dir/build.make CMakeFiles/url_parse_std_lib.dir/project/src/main.c.s
	$(MAKE) -f CMakeFiles/prog.dir/build.make CMakeFiles/prog.dir/project/src/main.c.s
.PHONY : project/src/main.c.s

project/src/query_info.o: project/src/query_info.c.o

.PHONY : project/src/query_info.o

# target to build an object file
project/src/query_info.c.o:
	$(MAKE) -f CMakeFiles/url_parse_std_lib.dir/build.make CMakeFiles/url_parse_std_lib.dir/project/src/query_info.c.o
.PHONY : project/src/query_info.c.o

project/src/query_info.i: project/src/query_info.c.i

.PHONY : project/src/query_info.i

# target to preprocess a source file
project/src/query_info.c.i:
	$(MAKE) -f CMakeFiles/url_parse_std_lib.dir/build.make CMakeFiles/url_parse_std_lib.dir/project/src/query_info.c.i
.PHONY : project/src/query_info.c.i

project/src/query_info.s: project/src/query_info.c.s

.PHONY : project/src/query_info.s

# target to generate assembly for a file
project/src/query_info.c.s:
	$(MAKE) -f CMakeFiles/url_parse_std_lib.dir/build.make CMakeFiles/url_parse_std_lib.dir/project/src/query_info.c.s
.PHONY : project/src/query_info.c.s

project/src/str.o: project/src/str.c.o

.PHONY : project/src/str.o

# target to build an object file
project/src/str.c.o:
	$(MAKE) -f CMakeFiles/url_parse_std_lib.dir/build.make CMakeFiles/url_parse_std_lib.dir/project/src/str.c.o
.PHONY : project/src/str.c.o

project/src/str.i: project/src/str.c.i

.PHONY : project/src/str.i

# target to preprocess a source file
project/src/str.c.i:
	$(MAKE) -f CMakeFiles/url_parse_std_lib.dir/build.make CMakeFiles/url_parse_std_lib.dir/project/src/str.c.i
.PHONY : project/src/str.c.i

project/src/str.s: project/src/str.c.s

.PHONY : project/src/str.s

# target to generate assembly for a file
project/src/str.c.s:
	$(MAKE) -f CMakeFiles/url_parse_std_lib.dir/build.make CMakeFiles/url_parse_std_lib.dir/project/src/str.c.s
.PHONY : project/src/str.c.s

project/src/tests.o: project/src/tests.cpp.o

.PHONY : project/src/tests.o

# target to build an object file
project/src/tests.cpp.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/project/src/tests.cpp.o
.PHONY : project/src/tests.cpp.o

project/src/tests.i: project/src/tests.cpp.i

.PHONY : project/src/tests.i

# target to preprocess a source file
project/src/tests.cpp.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/project/src/tests.cpp.i
.PHONY : project/src/tests.cpp.i

project/src/tests.s: project/src/tests.cpp.s

.PHONY : project/src/tests.s

# target to generate assembly for a file
project/src/tests.cpp.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/project/src/tests.cpp.s
.PHONY : project/src/tests.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... url_parse_std_lib"
	@echo "... tests"
	@echo "... prog"
	@echo "... project/src/main.o"
	@echo "... project/src/main.i"
	@echo "... project/src/main.s"
	@echo "... project/src/query_info.o"
	@echo "... project/src/query_info.i"
	@echo "... project/src/query_info.s"
	@echo "... project/src/str.o"
	@echo "... project/src/str.i"
	@echo "... project/src/str.s"
	@echo "... project/src/tests.o"
	@echo "... project/src/tests.i"
	@echo "... project/src/tests.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

